<a href="https://colab.research.google.com/github/MerveSevim44/deep_learning_workss/blob/main/15_assignment_new_patients_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Patients Diabetes Prediction

Hastanede işe başladınız.

Dr. Mehmet Efendi der ki benim burada hastalar için geliştirmiş olduğum bir model var. Seninle bu model bilgilerini paylaşacağım.

Hastalarımızı diyabet testine sokmadan önce modelin tahminlerini görmek istiyoruz. Fikir vermesi açısından göz önünde bulundurmak istiyoruz.

Verilecek olan hasta bilgilerini modele sormanı bekliyoruz.

Paylaşılan dosyalar:

- new_patients.csv
- diabetes_scaler.joblib
- diabetes_model.keras

# Imports

In [2]:
# !pip uninstall tf-keras
# !pip install tensorflow==2.16.1

In [3]:
import keras
import tensorflow as tf
print("Keras Current Version:", keras.__version__, "Tensorflow Current Version:", tf.__version__)

Keras Current Version: 3.10.0 Tensorflow Current Version: 2.19.0

In [4]:
import pandas as pd
from joblib import load
from tensorflow.keras.models import load_model

# Task 1: Scaler'ı yükleyiniz

In [6]:
scaler = load("/content/sample_data/diabetes_scaler.joblib")

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.2.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

# Task 2: Modeli yükleyiniz

In [7]:
model = load_model("/content/sample_data/diabetes_model.keras")

# Task 3: new_patients.csv dosyasını yükleyiniz

In [8]:
new_patients = pd.read_csv("/content/sample_data/new_patients.csv")
new_patients.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,139,75,0,0,25.6,0.167,29
1,0,180,78,63,14,59.4,2.420,25
2,4,147,74,25,293,34.9,0.385,30
3,0,98,82,15,84,NaN,0.299,22
4,1,107,72,30,82,30.8,0.821,24

# Task 4: Gerekli ön işleme işlemini yapınız

In [12]:
X_scaled = scaler.transform(new_patients)

# Task 5: Model ile yeni hastaların diyabet durumlarını tahmin ediniz

In [13]:
model.predict(X_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

array([[0.23639607],
       [0.99012667],
       [0.42975998],
       [       nan],
       [0.18260466],
       [0.19941358],
       [0.36935583],
       [0.7565832 ],
       [0.48401728],
       [0.06490432]], dtype=float32)

# Task 6: Tahminlerin birisi problemli gibi gözüküyor. Sebebi nedir? Düzeltiniz ve tekrar tahminde bulununuz.

In [14]:
new_patients.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         1
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [15]:
new_patients["BMI"] = new_patients["BMI"].fillna(new_patients["BMI"].mean())

In [16]:
new_patients.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [17]:
X_scaled = scaler.transform(new_patients)

In [18]:
model.predict(X_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

array([[0.23639607],
       [0.99012667],
       [0.42975998],
       [0.10464299],
       [0.18260466],
       [0.19941358],
       [0.36935583],
       [0.7565832 ],
       [0.48401728],
       [0.06490432]], dtype=float32)

# Task 7: Hastaların tahlil sonuçları aşağıda verilmiştir. 10 hasta için yapılan tahminlerin ne kadarı doğru? Tek tek yorumlayınız.

In [ ]:
# Hasta 1:  model: , gerçek: 0
# Hasta 2:  model: , gerçek: 1
# Hasta 3:  model: , gerçek: 0
# Hasta 4:  model: , gerçek: 0
# Hasta 5:  model: , gerçek: 0
# Hasta 6:  model: , gerçek: 0
# Hasta 7:  model: , gerçek: 1
# Hasta 8:  model: , gerçek: 1
# Hasta 9:  model: , gerçek: 1
# Hasta 10: model: , gerçek: 0